services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.150.1
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317"
    depends_on:
      - loki
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro

  prometheus:
    image: prom/prometheus:v3.11.2
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro

  loki:
    image: grafana/loki:3.7.1
    ports:
      - "3100:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./config/loki.yaml:/etc/loki/local-config.yaml:ro

  grafana:
    image: grafana/grafana:13.0.0
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro

volumes:
  grafana-data:
